### ISSUE TITLE
I installed all the python requirements, but confused about the script I need to actually run?

### ISSUE THREAD

**Issue by Jayinem** [AITUS95/MelonDS-Lime3DS-ScreenManager#1]
Sorry I'm not great with python or scripts like that. But I installed all python requirements your page sets. But it says you then need to run the script also, what is the script I need to run? I tried putting in cmd EmulatorBorderlessToggle.py but it didn't work.

thanks

**Comment by Jayinem** [comment]
Ok I downloaded EmulatorBorderlessToggle.py but I still am not sure how to run it.

**Comment by Jayinem** [comment]
Figured it out just had to change directories and do python EmulatorBorderlessToggle.py. Now it's working.

**Comment by AITUS95** [comment]
Ciao, tutto quello che devi fare è lanciare lo script da cmd dalla cartella
in cui risiede il file EmulatorBorderlessToggle.py, esempio: "python
EmulatorBorderlessToggle.py"

Il Gio 21 Nov 2024, 16:27 Jayinem ***@***.***> ha scritto:
